### ISSUE TITLE
name 'MessagePassing' is not defined pypots0.0.9

### ISSUE THREAD

**Issue by PsYaoyo** [WenjieDu/PyPOTS#30]
File "/home/ubuntu/miniconda3/envs/pypots/lib/python3.8/site-packages/pypots/classification/__init__.py", line 10, in <module>
    from pypots.classification.raindrop import Raindrop
  File "/home/ubuntu/miniconda3/envs/pypots/lib/python3.8/site-packages/pypots/classification/raindrop.py", line 83, in <module>
    class ObservationPropagation(MessagePassing):
NameError: name 'MessagePassing' is not defined

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by PsYaoyo** [comment]
miss some dependencies

**Comment by WenjieDu** [comment]
Hi @PsYaoyo, thank you for raising this issue. This error happens [here](https://github.com/WenjieDu/PyPOTS/blob/main/pypots/classification/raindrop.py#L30-L42). Starting from PyPOTS v0.0.9, we remove torch_geometric from the dependency file due to its long installation time. Users who want to use RainDrop in PyPOTS should install torch_geometric manually with `pip install torch_geometric` or `conda install -c pyg pyg`.
